$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$out = Join-Path $root "deploy\compose.host-drives.yml"
$lines = @(
  "# Generated by scripts/gen-host-drives.ps1. Do not edit.",
  "services:",
  "  foyer:",
  "    volumes:"
)
$n = 0
Get-PSDrive -PSProvider FileSystem | ForEach-Object {
  if ($_.Name -notmatch '^[A-Za-z]$') { return }
  $rootPath = "$($_.Name):\"
  if (-not (Test-Path -LiteralPath $rootPath)) { return }
  $letter = $_.Name.ToLower()
  $drv = $_.Name.ToUpper()
  $lines += "      - `"${drv}:/:/mnt/${letter}:ro`""
  $n++
}
if ($n -eq 0) {
  throw "no local drive letters found to bind into foyer"
}
$utf8 = New-Object System.Text.UTF8Encoding $false
[IO.File]::WriteAllLines($out, $lines, $utf8)
Write-Host "wrote $out ($n drives)"
